"""empty message

Revision ID: 34e59d01c042
Revises: None
Create Date: 2014-07-16 11:10:25.051307

"""

# revision identifiers, used by Alembic.
revision = '34e59d01c042'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('questions', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'questions')
    ### end Alembic commands ###
