"""empty message

Revision ID: 54e2468722f7
Revises: 1993c8d9b834
Create Date: 2014-08-12 20:24:40.063682

"""

# revision identifiers, used by Alembic.
revision = '54e2468722f7'
down_revision = '1993c8d9b834'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('num_de_paso', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'num_de_paso')
    ### end Alembic commands ###
